### PR TITLE
A few fixes/enhancements:

### LINKED ISSUE #9: Name, text and type regenerated every reload for a given pokemon
For a given pokemon URL, the title/text/type of the pokemon is regenerated each refresh, while the pokemon body image stays the same.  This makes it impossible to use the URL to share pokemans, since the title/type/description are not deterministic.

x270909744_cd078aad8f jpg pagespeed ic 6avpudizn3

FWIW, I disagree with issue #7, I think the markov chain generated sentences are pretty wacky and fun.  Zany, even.

### PR DESCRIPTION
**Pull request by ryansturmer**
- URLs now always include a tail, and if no tail is required, the id is an 'X'
- URLs now (optionally) include a random seed, which makes the text and types deterministic for a given URL
- Static dir selected for debugging automatically

This closes #9 

x270909744_cd078aad8f jpg pagespeed ic 6avpudizn3

### CODE REVIEW

**Comment by ohnorobo** [comment]
@cosileone I pulled the new stuff, but I'll leave restarting the process to you so I don't make a mess on your server.

**Comment by cosileone** [comment]
I have a tmux session called 'pokemon' in which you can just [ctrl-c] to interrupt and then run `'python __init__.py'` which is located in /var/www/pokemon/site/ folder.

In short:

```
tmux list-sessions
tmux attach -t pokemon
[ctrl-c] to interrupt flask app
git pull
python __init__.py (making sure you're in the site folder)
[ctrl-b] followed by 'd' to detach from tmux
```

:cool: 

~~sry for double underscore formatting but you get the idea~~

**Comment by ohnorobo** [comment]
gotcha, updated.

**Comment by ryansturmer** [comment]
aaaaah you guys should use a webserver with wsgi to run the pokamans!

**Comment by cosileone** [comment]
~~I have no idea what that means~~

Looked into it, will implement uWSGI when I get the chance

**Pull request merged**
