### PR TITLE
Hax Bean Poats.

### PR DESCRIPTION
**Pull request by wolfd**
#2 Because ali or alice won't do it.

### CODE REVIEW

**Comment by aceyoung9** [comment]
@wolfd will maybe actually get a shiny for this.

**Comment by ali** [comment]
@wolfd should have been my pick for captain. Gj bud.

**Comment by aceyoung9** [comment]
Captains have to leave their dorm rooms for the event.

**Comment by ali** [comment]
Their rooms?

**Comment by ali** [comment]
@ohnorobo We'll stop lol

**Comment by aceyoung9** [comment]
</thread>

@ohnorobo , a bunch of us are at HH if you want strange human companionship.

**Pull request merged**
